import { Injectable } from '@angular/core';
import { Observable } from 'rxjs/Observable';

export class Kind{
  name: string;
}

export const KINDER:  Kind[] = [
  { name: 'Abigail' },
  { name: 'Alaa_D.' },
  { name: 'Alaa_N.' },
  { name: 'Alexander' },
  { name: 'Amanuel' },
  { name: 'Amine' },
  { name: 'Amir' },
  { name: 'Andreea' },
  { name: 'Anis' },
  { name: 'Anita' },
  { name: 'Anna' },
  { name: 'Anna_Maita' },
  { name: 'Antoine' },
  { name: 'Arman_Nick' },
  { name: 'Atanas' },
  { name: 'Ayla_Su' },
  { name: 'Ayoub' },
  { name: 'Baye-Cheikh' },
  { name: 'Ben' },
  { name: 'Ben_Frederik' },
  { name: 'Bezawit' },
  { name: 'Bilal' },
  { name: 'Burcu' },
  { name: 'Christian' },
  { name: 'Conor' },
  { name: 'Damian' },
  { name: 'Dinu' },
  { name: 'Dorde' },
  { name: 'Dunya' },
  { name: 'Ebrar_Turap' },
  { name: 'Efe' },
  { name: 'Elia' },
  { name: 'Ella' },
  { name: 'Emma' },
  { name: 'Ever_Manuel' },
  { name: 'Felix' },
  { name: 'Finhas' },
  { name: 'Furat' },
  { name: 'Gina' },
  { name: 'Gordana' },
  { name: 'Hana' },
  { name: 'Hanna' },
  { name: 'Haydar-Can' },
  { name: 'Helena' },
  { name: 'Henriette' },
  { name: 'Hidayet' },
  { name: 'Ida' },
  { name: 'Ilja' },
  { name: 'Ilyas' },
  { name: 'Isabelle' },
  { name: 'Jan_David' },
  { name: 'Jason_Ryan' },
  { name: 'Joshua' },
  { name: 'Julia_A.' },
  { name: 'Julia_H.' },
  { name: 'Julia_R.' },
  { name: 'Julia_S.' },
  { name: 'Kaan' },
  { name: 'Katrin' },
  { name: 'Katya' },
  { name: 'Kaya' },
  { name: 'Kenan' },
  { name: 'Khalil' },
  { name: 'Kotaro' },
  { name: 'Krishna' },
  { name: 'Lara_H.' },
  { name: 'Lara_P.' },
  { name: 'Laura' },
  { name: 'Léane' },
  { name: 'Len_Jonah' },
  { name: 'Leon' },
  { name: 'Leonard' },
  { name: 'Leonie' },
  { name: 'Leslie' },
  { name: 'Lilijana' },
  { name: 'Linus' },
  { name: 'Lisa' },
  { name: 'Louis' },
  { name: 'Luca' },
  { name: 'Luise' },
  { name: 'Lukas' },
  { name: 'Lukas_Karl' },
  { name: 'Madina' },
  { name: 'Magnus' },
  { name: 'Maja' },
  { name: 'Malena' },
  { name: 'Maria_Juliette' },
  { name: 'Marko' },
  { name: 'Mathilde' },
  { name: 'Maya' },
  { name: 'Maysae' },
  { name: 'Mazaya' },
  { name: 'Mehmet_Furkan' },
  { name: 'Meltem' },
  { name: 'Meron' },
  { name: 'Meryem' },
  { name: 'Mia' },
  { name: 'Mia_Marie' },
  { name: 'Michael' },
  { name: 'Mikita' },
  { name: 'Mila_Mathilda' },
  { name: 'Milan' },
  { name: 'Mirena' },
  { name: 'Mohamed' },
  { name: 'Mohbin' },
  { name: 'Mojtaba' },
  { name: 'Muhammed_Riza' },
  { name: 'Mustafa' },
  { name: 'Nayla' },
  { name: 'Neda' },
  { name: 'Nesrin' },
  { name: 'Nico_Tim' },
  { name: 'Nino' },
  { name: 'Nisa' },
  { name: 'Nitem' },
  { name: 'Noah' },
  { name: 'Omid' },
  { name: 'Rayan_A.' },
  { name: 'Rayan_Z.' },
  { name: 'Rojin' },
  { name: 'Romeo' },
  { name: 'Safina' },
  { name: 'Sara' },
  { name: 'Sarah_Elisabeth' },
  { name: 'Selin' },
  { name: 'Semin' },
  { name: 'Shirinsakine' },
  { name: 'Simon' },
  { name: 'Sofia_Lissette' },
  { name: 'Sofian' },
  { name: 'Sohal' },
  { name: 'Sonja' },
  { name: 'Sophia' },
  { name: 'Stanislaw' },
  { name: 'Sude_Naz' },
  { name: 'Taqwa' },
  { name: 'Thibaut' },
  { name: 'Thuraya' },
  { name: 'Tijda' },
  { name: 'Timur' },
  { name: 'Tom' },
  { name: 'Valentina' },
  { name: 'Veronika_B.' },
  { name: 'Veronika_M.' },
  { name: 'Victor' },
  { name: 'Wiktoria' },
  { name: 'Xia_An' },
  { name: 'Yagis_Ege' },
  { name: 'Yasemin' },
  { name: 'Yasin' },
  { name: 'Yasmin_E.G.' },
  { name: 'Yasmin_E.H.' },
  { name: 'Yassin' },
  { name: 'Yigit' },
  { name: 'Youser' },
  { name: 'Yu_Lin' },
  { name: 'Yusuf' } 
];

@Injectable()
export class HService {

  constructor() { }
  getKinderList(): Kind[]{
    return KINDER; 
  }
}
